import { create } from 'zustand'
import { supabase } from '@/lib/supabase'
import type { Hero, HeroType } from '@/types'

interface HeroState {
  heroes: Hero[]
  loading: boolean
  fetchAll: () => Promise<void>
  fetchById: (heroId: string) => Promise<Hero | null>
  fetchByHandle: (handle: string) => Promise<Hero | null>
}

function mapHero(h: Record<string, unknown>): Hero {
  return {
    heroId: h.hero_id as string,
    handle: h.handle as string,
    name: h.name as string,
    title: (h.title as string) ?? null,
    bio: (h.bio as string) ?? null,
    cult: h.cult as string,
    avatarUrl: (h.avatar_url as string) ?? null,
    virtues: h.virtues as Hero['virtues'],
    mp: (h.mp as number) ?? 0,
    heroType: (h.hero_type as HeroType) ?? 'person',
    typeData: (h.type_data as Record<string, unknown>) ?? {},
    autoGenerated: (h.auto_generated as boolean) ?? false,
  }
}

export const useHeroStore = create<HeroState>()((set) => ({
  heroes: [],
  loading: false,

  fetchAll: async () => {
    set({ loading: true })
    const { data } = await supabase
      .from('heroes')
      .select('*')
      .order('mp', { ascending: false })

    const heroes: Hero[] = (data ?? []).map((h: Record<string, unknown>) => mapHero(h))
    set({ heroes, loading: false })
  },

  fetchById: async (heroId: string) => {
    const { data: h } = await supabase
      .from('heroes')
      .select('*')
      .eq('hero_id', heroId)
      .single()

    if (!h) return null
    return mapHero(h as Record<string, unknown>)
  },

  fetchByHandle: async (handle: string) => {
    const candidates = handle.startsWith('@') ? [handle, handle.slice(1)] : ['@' + handle, handle]
    for (const cand of candidates) {
      const { data: h } = await supabase
        .from('heroes')
        .select('*')
        .ilike('handle', cand)
        .maybeSingle()
      if (h) return mapHero(h as Record<string, unknown>)
    }
    return null
  },
}))
