import { create } from 'zustand'
import { supabase } from '@/lib/supabase'
import type { Quest, Hero, LootEntry, QuestMarket, QuestDetail, QuestRelic, QuestComment, Wager, QuestActivity, HeroType, SourceType } from '@/types'

interface QuestState {
  quests: Quest[]
  loading: boolean
  fetchQuests: () => Promise<void>
  fetchQuestDetail: (questId: string) => Promise<QuestDetail | null>
}

function mapHero(h: Record<string, unknown>): Hero {
  return {
    heroId: h.hero_id as string,
    handle: h.handle as string,
    name: h.name as string,
    title: (h.title as string) ?? null,
    bio: (h.bio as string) ?? null,
    cult: h.cult as string,
    avatarUrl: (h.avatar_url as string) ?? null,
    virtues: h.virtues as Hero['virtues'],
    mp: (h.mp as number) ?? 0,
    heroType: (h.hero_type as HeroType) ?? 'person',
    typeData: (h.type_data as Record<string, unknown>) ?? {},
    autoGenerated: (h.auto_generated as boolean) ?? false,
  }
}

export const useQuestStore = create<QuestState>()((set) => ({
  quests: [],
  loading: false,

  fetchQuests: async () => {
    set({ loading: true })

    const { data: questData } = await supabase
      .from('quests')
      .select('*')
      .order('volume', { ascending: false })

    if (!questData) { set({ loading: false }); return }

    const questIds = questData.map((q: { quest_id: string }) => q.quest_id)

    const [
      { data: markets },
      { data: heroLinks },
      { data: heroes },
      { data: loot },
    ] = await Promise.all([
      supabase.from('quest_markets').select('*').in('quest_id', questIds),
      supabase.from('quest_heroes').select('*').in('quest_id', questIds),
      supabase.from('heroes').select('*'),
      supabase.from('loot_table_entries').select('*').in('quest_id', questIds),
    ])

    const marketMap = new Map((markets ?? []).map((m: { quest_id: string }) => [m.quest_id, m]))
    const heroMap = new Map((heroes ?? []).map((h: Record<string, unknown>) => [h.hero_id, mapHero(h)]))
    const heroLinkMap = new Map<string, string[]>()
    for (const link of (heroLinks ?? [])) {
      const arr = heroLinkMap.get(link.quest_id) ?? []
      arr.push(link.hero_id)
      heroLinkMap.set(link.quest_id, arr)
    }
    const lootMap = new Map<string, LootEntry[]>()
    for (const l of (loot ?? [])) {
      const arr = lootMap.get(l.quest_id) ?? []
      arr.push(l)
      lootMap.set(l.quest_id, arr)
    }

    const quests: Quest[] = questData.map((q: Record<string, unknown>) => {
      const questHeroIds = heroLinkMap.get(q.quest_id as string) ?? []
      const questHeroes = questHeroIds.map((hid: string) => heroMap.get(hid)).filter(Boolean) as Hero[]
      const market = marketMap.get(q.quest_id as string) as Record<string, unknown> | undefined
      return {
        questId: q.quest_id as string,
        question: q.question as string,
        description: (q.description as string) ?? null,
        category: q.category as Quest['category'],
        status: q.status as Quest['status'],
        volume: (q.volume as number) ?? 0,
        engagement: (q.engagement as number) ?? 0,
        closesIn: (q.closes_in as string) ?? '',
        rarityDensity: (q.rarity_density as number) ?? 50,
        heroes: questHeroes,
        lootTable: lootMap.get(q.quest_id as string) ?? [],
        market: market ? {
          marketId: market.market_id as string,
          questId: market.quest_id as string,
          yesProbability: Number(market.yes_probability),
          noProbability: Number(market.no_probability),
          yesVolume: Number(market.yes_volume),
          noVolume: Number(market.no_volume),
        } as QuestMarket : null,
        sourceType: (q.source_type as SourceType) ?? 'manual',
        sourceUrl: (q.source_url as string) ?? null,
        confidenceScore: (q.confidence_score as number) ?? 50,
        resolutionOutcome: (q.resolution_outcome as Quest['resolutionOutcome']) ?? null,
      }
    })

    set({ quests, loading: false })
  },

  fetchQuestDetail: async (questId: string) => {
    const { data: q } = await supabase
      .from('quests')
      .select('*')
      .eq('quest_id', questId)
      .single()

    if (!q) return null

    const [
      { data: market },
      { data: heroLinks },
      { data: heroesData },
      { data: loot },
      { data: comments },
      { data: wagers },
      { data: activities },
    ] = await Promise.all([
      supabase.from('quest_markets').select('*').eq('quest_id', questId).maybeSingle(),
      supabase.from('quest_heroes').select('*').eq('quest_id', questId),
      supabase.from('heroes').select('*'),
      supabase.from('loot_table_entries').select('*').eq('quest_id', questId),
      supabase.from('quest_comments').select('*').eq('quest_id', questId).order('created_at', { ascending: false }),
      supabase.from('quest_wagers').select('*').eq('quest_id', questId).order('amount', { ascending: false }),
      supabase.from('quest_activities').select('*').eq('quest_id', questId).order('created_at', { ascending: false }),
    ])

    const heroMap = new Map((heroesData ?? []).map((h: Record<string, unknown>) => [h.hero_id, mapHero(h)]))
    const questHeroes = (heroLinks ?? []).map((l: { hero_id: string }) => heroMap.get(l.hero_id)).filter(Boolean) as Hero[]
    const linkedHeroIds = questHeroes.map((h) => h.heroId)

    const { data: heroItems } = await supabase
      .from('hero_items')
      .select('hero_id, item_id, items (name, description, icon, rarity, unique_effect)')
      .in('hero_id', linkedHeroIds)

    const relics: QuestRelic[] = []
    for (const hi of (heroItems ?? [])) {
      const item = (Array.isArray(hi.items) ? hi.items[0] : hi.items) as {
        name: string; description: string; icon: string; rarity: string; unique_effect: Record<string, unknown> | null
      } | null
      if (!item?.unique_effect) continue
      const ue = item.unique_effect as { name: string; description: string }
      const hero = heroMap.get(hi.hero_id)
      relics.push({
        name: item.name,
        description: item.description,
        icon: item.icon,
        rarity: item.rarity,
        heroName: hero?.name ?? 'Unknown',
        effectName: ue.name ?? null,
        effectDescription: ue.description ?? null,
      })
    }

    const mappedComments: QuestComment[] = (comments ?? []).map((c: {
      comment_id: string; quest_id: string; player_id: string;
      parent_id: string | null; text: string; upvotes: number;
      downvotes: number; created_at: string
    }) => ({
      commentId: c.comment_id,
      questId: c.quest_id,
      playerId: c.player_id,
      parentId: c.parent_id,
      text: c.text,
      upvotes: c.upvotes,
      downvotes: c.downvotes,
      createdAt: c.created_at,
      replies: [],
    }))

    const mappedWagers: Wager[] = (wagers ?? []).map((w: {
      wager_id: string; quest_id: string; player_id: string;
      player_hero_id: string | null; outcome: 'YES' | 'NO';
      amount: number; entry_probability: number | null;
      result: 'PENDING' | 'WON' | 'LOST'; payout: number;
      net_profit: number; placed_at: string; resolved_at: string | null
    }) => ({
      wagerId: w.wager_id,
      questId: w.quest_id,
      playerId: w.player_id,
      playerHeroId: w.player_hero_id,
      outcome: w.outcome,
      amount: w.amount,
      entryProbability: w.entry_probability,
      result: w.result,
      payout: w.payout,
      netProfit: w.net_profit,
      placedAt: w.placed_at,
      resolvedAt: w.resolved_at,
    }))

    const mappedActivities: QuestActivity[] = (activities ?? []).map((a: {
      activity_id: string; quest_id: string; type: string;
      text: string; player_id: string | null; amount: number | null;
      created_at: string
    }) => ({
      activityId: a.activity_id,
      questId: a.quest_id,
      type: a.type,
      text: a.text,
      playerId: a.player_id,
      amount: a.amount,
      createdAt: a.created_at,
    }))

    return {
      questId: q.quest_id,
      question: q.question,
      description: q.description,
      category: q.category,
      status: q.status,
      volume: q.volume,
      engagement: q.engagement,
      closesIn: q.closes_in,
      rarityDensity: q.rarity_density,
      heroes: questHeroes,
      lootTable: (loot ?? []) as LootEntry[],
      market: market ? {
        marketId: market.market_id,
        questId: market.quest_id,
        yesProbability: Number(market.yes_probability),
        noProbability: Number(market.no_probability),
        yesVolume: Number(market.yes_volume),
        noVolume: Number(market.no_volume),
      } : null,
      sourceType: (q.source_type as SourceType) ?? 'manual',
      sourceUrl: (q.source_url as string) ?? null,
      confidenceScore: (q.confidence_score as number) ?? 50,
      resolutionOutcome: (q.resolution_outcome as Quest['resolutionOutcome']) ?? null,
      relics,
      comments: mappedComments,
      leaderboard: mappedWagers,
      activities: mappedActivities,
    }
  },
}))
